src/Entity/Hotel.php
<?php

namespace App\Entity;

use App\Repository\HotelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HotelRepository::class)
 */
class Hotel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")

     */
    private $nbre_etoiles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_par_chambre;

    /**
     * @ORM\OneToMany(targetEntity=ReservationHotel::class, mappedBy="NomHotel")
     */
    private $reservationHotels;

    public function __construct()
    {
        $this->reservationHotels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNbreEtoiles(): ?int
    {
        return $this->nbre_etoiles;
    }

    public function setNbreEtoiles(int $nbre_etoiles): self
    {
        $this->nbre_etoiles = $nbre_etoiles;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPrixParChambre(): ?float
    {
        return $this->prix_par_chambre;
    }

    public function setPrixParChambre(float $prix_par_chambre): self
    {
        $this->prix_par_chambre = $prix_par_chambre;

        return $this;
    }

    /**
     * @return Collection<int, ReservationHotel>
     */
    public function getReservationHotels(): Collection
    {
        return $this->reservationHotels;
    }

    public function addReservationHotel(ReservationHotel $reservationHotel): self
    {
        if (!$this->reservationHotels->contains($reservationHotel)) {
            $this->reservationHotels[] = $reservationHotel;
            $reservationHotel->setNomHotel($this);
        }

        return $this;
    }

    public function removeReservationHotel(ReservationHotel $reservationHotel): self
    {
        if ($this->reservationHotels->removeElement($reservationHotel)) {
            // set the owning side to null (unless already changed)
            if ($reservationHotel->getNomHotel() === $this) {
                $reservationHotel->setNomHotel(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }

}

src/Form/HotelType.php
<?php

namespace App\Form;

use App\Entity\Hotel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HotelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('nbre_etoiles')
            ->add('adresse')
            ->add('prix_par_chambre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Hotel::class,
        ]);
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use App\Entity\Hotel;
use App\Form\HotelType;
use App\Repository\HotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/hotel")
 */
class HotelController extends AbstractController
{
    /**
     * @Route("/", name="app_hotel_index", methods={"GET"})
     */
    public function index(HotelRepository $hotelRepository): Response
    {
        return $this->render('hotel/index.html.twig', [
            'hotels' => $hotelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/Back", name="app_hotel_indexBack", methods={"GET"})
     */
    public function indexBack(HotelRepository $hotelRepository): Response
    {
        return $this->render('hotel/indexBack.html.twig', [
            'hotels' => $hotelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_hotel_new", methods={"GET", "POST"})
     */
    public function new(Request $request, HotelRepository $hotelRepository): Response
    {
        $hotel = new Hotel();
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hotelRepository->add($hotel);
            return $this->redirectToRoute('app_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hotel/new.html.twig', [
            'hotel' => $hotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_hotel_show", methods={"GET"})
     */
    public function show(Hotel $hotel): Response
    {
        return $this->render('hotel/show.html.twig', [
            'hotel' => $hotel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_hotel_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Hotel $hotel, HotelRepository $hotelRepository): Response
    {
        $form = $this->createForm(HotelType::class, $hotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hotelRepository->add($hotel);
            return $this->redirectToRoute('app_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hotel/edit.html.twig', [
            'hotel' => $hotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_hotel_delete", methods={"POST"})
     */
    public function delete(Request $request, Hotel $hotel, HotelRepository $hotelRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hotel->getId(), $request->request->get('_token'))) {
            $hotelRepository->remove($hotel);
        }

        return $this->redirectToRoute('app_hotel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/hotel/_delete_form.html.twig
<form method="post" action="{{ path('app_hotel_delete', {'id': hotel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hotel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hotel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hotel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hotel{% endblock %}

{% block body %}
    <div class="dash">
        <div class="dash-nav dash-nav-dark">
            <header>
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="index.html" class="spur-logo"><i class="fas fa-bolt"></i> <span>SkyTravel</span></a>
            </header>

            <nav class="dash-nav-list">
                <a href="usersA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Users </a>
                <a href="hotelsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Hotels </a>
                <a href="VolA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Vols </a>
                <a href="evenementsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Evenements </a>
                <a href="restaurantsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Restaurants </a>
                <a href="excursionsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Excursions </a>


                <div class="dash-nav-dropdown">
                    <a href="#!" class="dash-nav-item dash-nav-dropdown-toggle">
                        <i class="fas fa-info"></i> About </a>
                    <div class="dash-nav-dropdown-menu">
                        <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="dash-nav-dropdown-item">GitHub</a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="dash-app">
            <header class="dash-toolbar">
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="#!" class="searchbox-toggle">
                    <i class="fas fa-search"></i>
                </a>
                <form class="searchbox" action="#!">
                    <a href="#!" class="searchbox-toggle"> <i class="fas fa-arrow-left"></i> </a>
                    <button type="submit" class="searchbox-submit"> <i class="fas fa-search"></i> </button>
                    <input type="text" class="searchbox-input" placeholder="type to search">
                </form>
                <div class="tools">
                    <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="tools-item">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="#!" class="tools-item">
                        <i class="fas fa-bell"></i>
                        <i class="tools-item-count">4</i>
                    </a>
                    <div class="dropdown tools-item">
                        <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="#!">Profile</a>
                            <a class="dropdown-item" href="login.html">Logout</a>
                        </div>
                    </div>
                </div>
            </header>

            <h1>Edit Hotel</h1>
            {{ include('hotel/_form.html.twig', {'button_label': 'Update'}) }}
            <a href="{{ path('app_hotel_index') }}">back to list</a>
            {{ include('hotel/_delete_form.html.twig') }}
    </div>

{% endblock %}

templates/hotel/index.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}List Hotel{% endblock %}

{% block body %}
        </header>

        <h1>Hotel </h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nbre_etoiles</th>
                <th>Adresse</th>
                <th>Prix_par_chambre</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for hotel in hotels %}
                <tr>
                    <td>{{ hotel.id }}</td>
                    <td>{{ hotel.nom }}</td>
                    <td>{{ hotel.nbreEtoiles }}</td>
                    <td>{{ hotel.adresse }}</td>
                    <td>{{ hotel.prixParChambre }}</td>
                    <td>
                        <a href="{{ path('app_hotel_show', {'id': hotel.id}) }}">show</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/hotel/indexBack.html.twig
{% extends 'base.html.twig' %}

{% block title %}List Hotel{% endblock %}

{% block body %}
    <div class="dash">
    <div class="dash-nav dash-nav-dark">
        <header>
            <a href="#!" class="menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <a href="index.html" class="spur-logo"><i class="fas fa-bolt"></i> <span>SkyTravel</span></a>
        </header>

        <nav class="dash-nav-list">
            <a href="usersA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Users </a>
            <a href="hotelsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Hotels </a>
            <a href="VolA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Vols </a>
            <a href="evenementsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Evenements </a>
            <a href="restaurantsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Restaurants </a>
            <a href="excursionsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Excursions </a>


            <div class="dash-nav-dropdown">
                <a href="#!" class="dash-nav-item dash-nav-dropdown-toggle">
                    <i class="fas fa-info"></i> About </a>
                <div class="dash-nav-dropdown-menu">
                    <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="dash-nav-dropdown-item">GitHub</a>
                </div>
            </div>
        </nav>
    </div>
    <div class="dash-app">
        <header class="dash-toolbar">
            <a href="#!" class="menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <a href="#!" class="searchbox-toggle">
                <i class="fas fa-search"></i>
            </a>
            <form class="searchbox" action="#!">
                <a href="#!" class="searchbox-toggle"> <i class="fas fa-arrow-left"></i> </a>
                <button type="submit" class="searchbox-submit"> <i class="fas fa-search"></i> </button>
                <input type="text" class="searchbox-input" placeholder="type to search">
            </form>
            <div class="tools">
                <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="tools-item">
                    <i class="fab fa-github"></i>
                </a>
                <a href="#!" class="tools-item">
                    <i class="fas fa-bell"></i>
                    <i class="tools-item-count">4</i>
                </a>
                <div class="dropdown tools-item">
                    <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <a class="dropdown-item" href="#!">Profile</a>
                        <a class="dropdown-item" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </header>

        <h1>Hotel </h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nbre_etoiles</th>
                <th>Adresse</th>
                <th>Prix_par_chambre</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for hotel in hotels %}
                <tr>
                    <td>{{ hotel.id }}</td>
                    <td>{{ hotel.nom }}</td>
                    <td>{{ hotel.nbreEtoiles }}</td>
                    <td>{{ hotel.adresse }}</td>
                    <td>{{ hotel.prixParChambre }}</td>
                    <td>
                        <a href="{{ path('app_hotel_show', {'id': hotel.id}) }}">show</a>
                        <a href="{{ path('app_hotel_edit', {'id': hotel.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_hotel_new') }}">Create new</a>
    </div>

{% endblock %}

templates/hotel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Hotel{% endblock %}

{% block body %}
    <div class="dash">
        <div class="dash-nav dash-nav-dark">
            <header>
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="index.html" class="spur-logo"><i class="fas fa-bolt"></i> <span>SkyTravel</span></a>
            </header>

            <nav class="dash-nav-list">
                <a href="usersA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Users </a>
                <a href="hotelsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Hotels </a>
                <a href="VolA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Vols </a>
                <a href="evenementsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Evenements </a>
                <a href="restaurantsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Restaurants </a>
                <a href="excursionsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Excursions </a>


                <div class="dash-nav-dropdown">
                    <a href="#!" class="dash-nav-item dash-nav-dropdown-toggle">
                        <i class="fas fa-info"></i> About </a>
                    <div class="dash-nav-dropdown-menu">
                        <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="dash-nav-dropdown-item">GitHub</a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="dash-app">
            <header class="dash-toolbar">
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="#!" class="searchbox-toggle">
                    <i class="fas fa-search"></i>
                </a>
                <form class="searchbox" action="#!">
                    <a href="#!" class="searchbox-toggle"> <i class="fas fa-arrow-left"></i> </a>
                    <button type="submit" class="searchbox-submit"> <i class="fas fa-search"></i> </button>
                    <input type="text" class="searchbox-input" placeholder="type to search">
                </form>
                <div class="tools">
                    <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="tools-item">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="#!" class="tools-item">
                        <i class="fas fa-bell"></i>
                        <i class="tools-item-count">4</i>
                    </a>
                    <div class="dropdown tools-item">
                        <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="#!">Profile</a>
                            <a class="dropdown-item" href="login.html">Logout</a>
                        </div>
                    </div>
                </div>
            </header>



            <h1>Create new Hotel</h1>

            {{ include('hotel/_form.html.twig') }}

            <a href="{{ path('app_hotel_index') }}">back to list</a>
        </div>
    </div>

{% endblock %}

templates/hotel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hotel{% endblock %}

{% block body %}
    <h1>Hotel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hotel.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ hotel.nom }}</td>
            </tr>
            <tr>
                <th>Nbre_etoiles</th>
                <td>{{ hotel.nbreEtoiles }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ hotel.adresse }}</td>
            </tr>
            <tr>
                <th>Prix_par_chambre</th>
                <td>{{ hotel.prixParChambre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_hotel_index') }}">back to list</a>

    <a href="{{ path('app_hotel_edit', {'id': hotel.id}) }}">edit</a>

    {{ include('hotel/_delete_form.html.twig') }}
{% endblock %}