src/Entity/ReservationHotel.php
<?php

namespace App\Entity;

use App\Repository\ReservationHotelRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=ReservationHotelRepository::class)
 */
class ReservationHotel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Date Debut is required")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Date Fin is required")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Type is required")
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Nombre de Chambre is required")
     */
    private $nombre_chambre;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="reservationHotels")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Nom Hotel is required")
     */
    private $NomHotel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getNombreChambre(): ?int
    {
        return $this->nombre_chambre;
    }

    public function setNombreChambre(int $nombre_chambre): self
    {
        $this->nombre_chambre = $nombre_chambre;

        return $this;
    }

    public function getNomHotel(): ?Hotel
    {
        return $this->NomHotel;
    }

    public function setNomHotel(?Hotel $NomHotel): self
    {
        $this->NomHotel = $NomHotel;

        return $this;
    }
}

src/Form/ReservationHotelType.php
<?php

namespace App\Form;

use App\Entity\ReservationHotel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationHotelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('type')
            ->add('nombre_chambre')
            ->add('NomHotel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ReservationHotel::class,
        ]);
    }
}

src/Controller/ReservationHotelController.php
<?php

namespace App\Controller;

use App\Entity\ReservationHotel;
use App\Form\ReservationHotelType;
use App\Repository\ReservationHotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation/hotel")
 */
class ReservationHotelController extends AbstractController
{
    /**
     * @Route("/", name="app_reservation_hotel_index", methods={"GET"})
     */
    public function index(ReservationHotelRepository $reservationHotelRepository): Response
    {
        return $this->render('reservation_hotel/index.html.twig', [
            'reservation_hotels' => $reservationHotelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_reservation_hotel_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ReservationHotelRepository $reservationHotelRepository): Response
    {
        $reservationHotel = new ReservationHotel();
        $form = $this->createForm(ReservationHotelType::class, $reservationHotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationHotelRepository->add($reservationHotel);
            return $this->redirectToRoute('app_reservation_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation_hotel/new.html.twig', [
            'reservation_hotel' => $reservationHotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_reservation_hotel_show", methods={"GET"})
     */
    public function show(ReservationHotel $reservationHotel): Response
    {
        return $this->render('reservation_hotel/show.html.twig', [
            'reservation_hotel' => $reservationHotel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_reservation_hotel_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ReservationHotel $reservationHotel, ReservationHotelRepository $reservationHotelRepository): Response
    {
        $form = $this->createForm(ReservationHotelType::class, $reservationHotel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationHotelRepository->add($reservationHotel);
            return $this->redirectToRoute('app_reservation_hotel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation_hotel/edit.html.twig', [
            'reservation_hotel' => $reservationHotel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_reservation_hotel_delete", methods={"POST"})
     */
    public function delete(Request $request, ReservationHotel $reservationHotel, ReservationHotelRepository $reservationHotelRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservationHotel->getId(), $request->request->get('_token'))) {
            $reservationHotelRepository->remove($reservationHotel);
        }

        return $this->redirectToRoute('app_reservation_hotel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation_hotel/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_hotel_delete', {'id': reservation_hotel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation_hotel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation_hotel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation_hotel/edit.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Edit ReservationHotel{% endblock %}

{% block body %}
    <h1>Edit ReservationHotel</h1>

    {{ include('reservation_hotel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_hotel_index') }}">back to list</a>

    {{ include('reservation_hotel/_delete_form.html.twig') }}
{% endblock %}

templates/reservation_hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation Hotel{% endblock %}

{% block body %}
    <div class="dash">
    <div class="dash-nav dash-nav-dark">
        <header>
            <a href="#!" class="menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <a href="index.html" class="spur-logo"><i class="fas fa-bolt"></i> <span>SkyTravel</span></a>
        </header>

        <nav class="dash-nav-list">
            <a href="usersA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Users </a>
            <a href="hotelsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Hotels </a>
            <a href="VolA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Vols </a>
            <a href="evenementsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Evenements </a>
            <a href="restaurantsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Restaurants </a>
            <a href="excursionsA.html" class="dash-nav-item">
                <i class="fas fa-home"></i> Excursions </a>


            <div class="dash-nav-dropdown">
                <a href="#!" class="dash-nav-item dash-nav-dropdown-toggle">
                    <i class="fas fa-info"></i> About </a>
                <div class="dash-nav-dropdown-menu">
                    <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="dash-nav-dropdown-item">GitHub</a>
                </div>
            </div>
        </nav>
    </div>
    <div class="dash-app">
        <header class="dash-toolbar">
            <a href="#!" class="menu-toggle">
                <i class="fas fa-bars"></i>
            </a>
            <a href="#!" class="searchbox-toggle">
                <i class="fas fa-search"></i>
            </a>
            <form class="searchbox" action="#!">
                <a href="#!" class="searchbox-toggle"> <i class="fas fa-arrow-left"></i> </a>
                <button type="submit" class="searchbox-submit"> <i class="fas fa-search"></i> </button>
                <input type="text" class="searchbox-input" placeholder="type to search">
            </form>
            <div class="tools">
                <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="tools-item">
                    <i class="fab fa-github"></i>
                </a>
                <a href="#!" class="tools-item">
                    <i class="fas fa-bell"></i>
                    <i class="tools-item-count">4</i>
                </a>
                <div class="dropdown tools-item">
                    <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                        <a class="dropdown-item" href="#!">Profile</a>
                        <a class="dropdown-item" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </header>
        <h1>Reservation Hotel</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Type</th>
                <th>Nombre_chambre</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for reservation_hotel in reservation_hotels %}
                <tr>
                    <td>{{ reservation_hotel.id }}</td>
                    <td>{{ reservation_hotel.dateDebut ? reservation_hotel.dateDebut|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation_hotel.dateFin ? reservation_hotel.dateFin|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation_hotel.type }}</td>
                    <td>{{ reservation_hotel.nombreChambre }}</td>
                    <td>
                        <a href="{{ path('app_reservation_hotel_show', {'id': reservation_hotel.id}) }}">show</a>
                        <a href="{{ path('app_reservation_hotel_edit', {'id': reservation_hotel.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_reservation_hotel_new') }}">Create new</a>
    </div>

{% endblock %}

templates/reservation_hotel/new.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}New ReservationHotel{% endblock %}

{% block body %}
    <h1>Create new ReservationHotel</h1>

    {{ include('reservation_hotel/_form.html.twig') }}

{% endblock %}

templates/reservation_hotel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation Hotel{% endblock %}

{% block body %}
    <div class="dash">
        <div class="dash-nav dash-nav-dark">
            <header>
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="index.html" class="spur-logo"><i class="fas fa-bolt"></i> <span>SkyTravel</span></a>
            </header>

            <nav class="dash-nav-list">
                <a href="usersA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Users </a>
                <a href="hotelsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Hotels </a>
                <a href="{{ path('app_vol_index') }}" class="dash-nav-item">
                    <i class="fas fa-home"></i> Vols </a>
                <a href="evenementsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Evenements </a>
                <a href="restaurantsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Restaurants </a>
                <a href="excursionsA.html" class="dash-nav-item">
                    <i class="fas fa-home"></i> Excursions </a>


                <div class="dash-nav-dropdown">
                    <a href="#!" class="dash-nav-item dash-nav-dropdown-toggle">
                        <i class="fas fa-info"></i> About </a>
                    <div class="dash-nav-dropdown-menu">
                        <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="dash-nav-dropdown-item">GitHub</a>
                    </div>
                </div>
            </nav>
        </div>
        <div class="dash-app">
            <header class="dash-toolbar">
                <a href="#!" class="menu-toggle">
                    <i class="fas fa-bars"></i>
                </a>
                <a href="#!" class="searchbox-toggle">
                    <i class="fas fa-search"></i>
                </a>
                <form class="searchbox" action="#!">
                    <a href="#!" class="searchbox-toggle"> <i class="fas fa-arrow-left"></i> </a>
                    <button type="submit" class="searchbox-submit"> <i class="fas fa-search"></i> </button>
                    <input type="text" class="searchbox-input" placeholder="type to search">
                </form>
                <div class="tools">
                    <a href="https://github.com/rihab-gif/Tech-Plus-Web" target="_blank" class="tools-item">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="#!" class="tools-item">
                        <i class="fas fa-bell"></i>
                        <i class="tools-item-count">4</i>
                    </a>
                    <div class="dropdown tools-item">
                        <a href="#" class="" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                            <a class="dropdown-item" href="#!">Profile</a>
                            <a class="dropdown-item" href="login.html">Logout</a>
                        </div>
                    </div>
                </div>
            </header>

            <h1>ReservationHotel</h1>

            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ reservation_hotel.id }}</td>
                </tr>
                <tr>
                    <th>Date_debut</th>
                    <td>{{ reservation_hotel.dateDebut ? reservation_hotel.dateDebut|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Date_fin</th>
                    <td>{{ reservation_hotel.dateFin ? reservation_hotel.dateFin|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Type</th>
                    <td>{{ reservation_hotel.type }}</td>
                </tr>
                <tr>
                    <th>Nombre_chambre</th>
                    <td>{{ reservation_hotel.nombreChambre }}</td>
                </tr>
                </tbody>
            </table>

            <a href="{{ path('app_reservation_hotel_index') }}">back to list</a>

            <a href="{{ path('app_reservation_hotel_edit', {'id': reservation_hotel.id}) }}">edit</a>

            {{ include('reservation_hotel/_delete_form.html.twig') }}
            </table>

        </div>
    </div>

    </div>
    </div>

{% endblock %}